package com.generator.pojo;

import java.util.Date;

public class Logs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_id
     *
     * @mbggenerated
     */
    private String logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_title
     *
     * @mbggenerated
     */
    private String logTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_summary
     *
     * @mbggenerated
     */
    private String logSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_content
     *
     * @mbggenerated
     */
    private String logContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_created
     *
     * @mbggenerated
     */
    private Date logCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_update
     *
     * @mbggenerated
     */
    private Date logUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_id
     *
     * @return the value of logs.log_id
     *
     * @mbggenerated
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_id
     *
     * @param logId the value for logs.log_id
     *
     * @mbggenerated
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_title
     *
     * @return the value of logs.log_title
     *
     * @mbggenerated
     */
    public String getLogTitle() {
        return logTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_title
     *
     * @param logTitle the value for logs.log_title
     *
     * @mbggenerated
     */
    public void setLogTitle(String logTitle) {
        this.logTitle = logTitle == null ? null : logTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_summary
     *
     * @return the value of logs.log_summary
     *
     * @mbggenerated
     */
    public String getLogSummary() {
        return logSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_summary
     *
     * @param logSummary the value for logs.log_summary
     *
     * @mbggenerated
     */
    public void setLogSummary(String logSummary) {
        this.logSummary = logSummary == null ? null : logSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_content
     *
     * @return the value of logs.log_content
     *
     * @mbggenerated
     */
    public String getLogContent() {
        return logContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_content
     *
     * @param logContent the value for logs.log_content
     *
     * @mbggenerated
     */
    public void setLogContent(String logContent) {
        this.logContent = logContent == null ? null : logContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_created
     *
     * @return the value of logs.log_created
     *
     * @mbggenerated
     */
    public Date getLogCreated() {
        return logCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_created
     *
     * @param logCreated the value for logs.log_created
     *
     * @mbggenerated
     */
    public void setLogCreated(Date logCreated) {
        this.logCreated = logCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_update
     *
     * @return the value of logs.log_update
     *
     * @mbggenerated
     */
    public Date getLogUpdate() {
        return logUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_update
     *
     * @param logUpdate the value for logs.log_update
     *
     * @mbggenerated
     */
    public void setLogUpdate(Date logUpdate) {
        this.logUpdate = logUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.count
     *
     * @return the value of logs.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.count
     *
     * @param count the value for logs.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}