package com.gao.ssm.module.mapper.logs;

import com.gao.ssm.module.pojo.logs.Logs;

import java.util.List;

public interface LogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs
     *
     * @mbggenerated
     */
    int insert(Logs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs
     *
     * @mbggenerated
     */
    int insertSelective(Logs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs
     *
     * @mbggenerated
     */
    Logs selectByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Logs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Logs record);

    List<Logs> findAll();

    /**
     * 定义分页功能
     * @param logs
     * @param pageNum
     * @param pageSize
     * @return
     */

//    public Pager<Logs> findAll(List<Logs> logs,int pageNum,int pageSize);
}