package com.gao.ssm.module.pojo.logs;

import java.util.Date;

public class Logs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_id
     *
     * @mbggenerated
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_name
     *
     * @mbggenerated
     */
    private String logName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_summary
     *
     * @mbggenerated
     */
    private String logSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_url
     *
     * @mbggenerated
     */
    private String logUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_created
     *
     * @mbggenerated
     */
    private Date logCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_update
     *
     * @mbggenerated
     */
    private Date logUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_id
     *
     * @return the value of logs.log_id
     *
     * @mbggenerated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_id
     *
     * @param logId the value for logs.log_id
     *
     * @mbggenerated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_name
     *
     * @return the value of logs.log_name
     *
     * @mbggenerated
     */
    public String getLogName() {
        return logName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_name
     *
     * @param logName the value for logs.log_name
     *
     * @mbggenerated
     */
    public void setLogName(String logName) {
        this.logName = logName == null ? null : logName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_summary
     *
     * @return the value of logs.log_summary
     *
     * @mbggenerated
     */
    public String getLogSummary() {
        return logSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_summary
     *
     * @param logSummary the value for logs.log_summary
     *
     * @mbggenerated
     */
    public void setLogSummary(String logSummary) {
        this.logSummary = logSummary == null ? null : logSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_url
     *
     * @return the value of logs.log_url
     *
     * @mbggenerated
     */
    public String getLogUrl() {
        return logUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_url
     *
     * @param logUrl the value for logs.log_url
     *
     * @mbggenerated
     */
    public void setLogUrl(String logUrl) {
        this.logUrl = logUrl == null ? null : logUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_created
     *
     * @return the value of logs.log_created
     *
     * @mbggenerated
     */
    public Date getLogCreated() {
        return logCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_created
     *
     * @param logCreated the value for logs.log_created
     *
     * @mbggenerated
     */
    public void setLogCreated(Date logCreated) {
        this.logCreated = logCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_update
     *
     * @return the value of logs.log_update
     *
     * @mbggenerated
     */
    public Date getLogUpdate() {
        return logUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_update
     *
     * @param logUpdate the value for logs.log_update
     *
     * @mbggenerated
     */
    public void setLogUpdate(Date logUpdate) {
        this.logUpdate = logUpdate;
    }
}