package com.gao.ssm.module.pojo.menu;

public class BaseMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.menu_id
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.p_menu_id
     *
     * @mbggenerated
     */
    private Integer pMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.menu_name
     *
     * @mbggenerated
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.menu_url
     *
     * @mbggenerated
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.menu_type
     *
     * @mbggenerated
     */
    private String menuType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.menu_id
     *
     * @return the value of base_menu.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.menu_id
     *
     * @param menuId the value for base_menu.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.p_menu_id
     *
     * @return the value of base_menu.p_menu_id
     *
     * @mbggenerated
     */
    public Integer getpMenuId() {
        return pMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.p_menu_id
     *
     * @param pMenuId the value for base_menu.p_menu_id
     *
     * @mbggenerated
     */
    public void setpMenuId(Integer pMenuId) {
        this.pMenuId = pMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.menu_name
     *
     * @return the value of base_menu.menu_name
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.menu_name
     *
     * @param menuName the value for base_menu.menu_name
     *
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.menu_url
     *
     * @return the value of base_menu.menu_url
     *
     * @mbggenerated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.menu_url
     *
     * @param menuUrl the value for base_menu.menu_url
     *
     * @mbggenerated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.menu_type
     *
     * @return the value of base_menu.menu_type
     *
     * @mbggenerated
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.menu_type
     *
     * @param menuType the value for base_menu.menu_type
     *
     * @mbggenerated
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType == null ? null : menuType.trim();
    }
}